Update arrays.js
For function getName(), the parameter should be an array of arrays, since the function utilize find() method.
The original parameter "dog" may imply that the method takes a dog object - which  will cause an error
Error: dog.find is not a function